### PR TITLE
Update values.py for RAM_HD 2024

### PR DESCRIPTION
**Pull request by tmcmenam**

### CODE REVIEW

**Comment by tmcmenam** [comment]
{'carParams': {'alternativeExperience': 1,
               'autoResumeSng': True,
               'carFingerprint': 'mock',
               'carFw': [{'address': 1863,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'68641704AA',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1223,
                          'subAddress': 0},
                         {'address': 1858,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'combinationMeter',
                          'fwVersion': b'68628474AB',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1218,
                          'subAddress': 0},
                         {'address': 1875,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'68615489AB',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1235,
                          'subAddress': 0},
                         {'address': 1889,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'68534023AC',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1249,
                          'subAddress': 0},
                         {'address': 1860,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'srs',
                          'fwVersion': b'68428503AA',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1220,
                          'subAddress': 0},
                         {'address': 2016,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'engine',
                          'fwVersion': b'52370491AA',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 2024,
                          'subAddress': 0}],
               'carName': 'mock',
               'carVin': '00000000000000000',
               'centerToFront': 1.350000023841858,
               'communityFeatureDEPRECATED': False,
               'dashcamOnly': False,
               'directAccelControlDEPRECATED': False,
               'enableApgsDEPRECATED': False,
               'enableBsm': False,
               'enableCameraDEPRECATED': False,
               'enableDsu': False,
               'enableGasInterceptor': False,
               'experimentalLongitudinalAvailable': False,
               'fingerprintSource': 'can',
               'flags': 0,
               'fuzzyFingerprint': False,
               'hasStockCameraDEPRECATED': False,
               'isPandaBlackDEPRECATED': False,
               'lateralTuning': {'pid': {'kf': 0.0}},
               'longitudinalActuatorDelayLowerBound': 0.15000000596046448,
               'longitudinalActuatorDelayUpperBound': 0.15000000596046448,
               'longitudinalTuning': {'deadzoneBP': [0.0], 'deadzoneV': [0.0], 'kf': 1.0, 'kiBP': [0.0], 'kiV': [1.0], 'kpBP': [0.0], 'kpV': [1.0]},
               'mass': 1700.0,
               'maxLateralAccel': 10.0,
               'maxSteeringAngleDegDEPRECATED': 0.0,
               'minEnableSpeed': -1.0,
               'minSpeedCanDEPRECATED': 0.0,
               'minSteerSpeed': 0.0,
               'networkLocation': 'fwdCamera',
               'notCar': False,
               'openpilotLongitudinalControl': False,
               'pcmCruise': True,
               'radarTimeStep': 0.05000000074505806,
               'radarUnavailable': False,
               'rotationalInertia': 2906.976806640625,
               'safetyConfigs': [{'safetyModel': 'noOutput', 'safetyParam': 0, 'safetyParam2DEPRECATED': 0, 'safetyParamDEPRECATED': 0}],
               'safetyModelDEPRECATED': 'silent',
               'safetyModelPassiveDEPRECATED': 'silent',
               'safetyParamDEPRECATED': 0,
               'startAccel': 0.0,
               'startingAccelRateDEPRECATED': 0.0,
               'startingState': False,
               'steerActuatorDelay': 0.0,
               'steerControlType': 'torque',
               'steerLimitAlert': False,
               'steerLimitTimer': 1.0,
               'steerRateCostDEPRECATED': 0.0,
               'steerRatio': 13.0,
               'steerRatioRear': 0.0,
               'stopAccel': -2.0,
               'stoppingControl': True,
               'stoppingDecelRate': 0.800000011920929,
               'tireStiffnessFactor': 0.0,
               'tireStiffnessFront': 1000000.0,
               'tireStiffnessRear': 1000000.0,
               'transmissionType': 'unknown',
               'vEgoStarting': 0.5,
               'vEgoStopping': 0.5,
               'wheelSpeedFactor': 1.0,
               'wheelbase': 2.700000047683716},
 'logMonoTime': 36563244151,
 'valid': True}
{'carParams': {'alternativeExperience': 1,
               'autoResumeSng': True,
               'carFingerprint': 'mock',
               'carFw': [{'address': 1863,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'68641704AA',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1223,
                          'subAddress': 0},
                         {'address': 1858,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'combinationMeter',
                          'fwVersion': b'68628474AB',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1218,
                          'subAddress': 0},
                         {'address': 1875,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'68615489AB',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1235,
                          'subAddress': 0},
                         {'address': 1889,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'68534023AC',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1249,
                          'subAddress': 0},
                         {'address': 1860,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'srs',
                          'fwVersion': b'68428503AA',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 1220,
                          'subAddress': 0},
                         {'address': 2016,
                          'brand': 'chrysler',
                          'bus': 0,
                          'ecu': 'engine',
                          'fwVersion': b'52370491AA',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf12'],
                          'responseAddress': 2024,
                          'subAddress': 0}],
               'carName': 'mock',
               'carVin': '00000000000000000',
               'centerToFront': 1.350000023841858,
               'communityFeatureDEPRECATED': False,
               'dashcamOnly': False,
               'directAccelControlDEPRECATED': False,
               'enableApgsDEPRECATED': False,
               'enableBsm': False,
               'enableCameraDEPRECATED': False,
               'enableDsu': False,
               'enableGasInterceptor': False,
               'experimentalLongitudinalAvailable': False,
               'fingerprintSource': 'can',
               'flags': 0,
               'fuzzyFingerprint': False,
               'hasStockCameraDEPRECATED': False,
               'isPandaBlackDEPRECATED': False,
               'lateralTuning': {'pid': {'kf': 0.0}},
               'longitudinalActuatorDelayLowerBound': 0.15000000596046448,
               'longitudinalActuatorDelayUpperBound': 0.15000000596046448,
               'longitudinalTuning': {'deadzoneBP': [0.0], 'deadzoneV': [0.0], 'kf': 1.0, 'kiBP': [0.0], 'kiV': [1.0], 'kpBP': [0.0], 'kpV': [1.0]},
               'mass': 1700.0,
               'maxLateralAccel': 10.0,
               'maxSteeringAngleDegDEPRECATED': 0.0,
               'minEnableSpeed': -1.0,
               'minSpeedCanDEPRECATED': 0.0,
               'minSteerSpeed': 0.0,
               'networkLocation': 'fwdCamera',
               'notCar': False,
               'openpilotLongitudinalControl': False,
               'pcmCruise': True,
               'radarTimeStep': 0.05000000074505806,
               'radarUnavailable': False,
               'rotationalInertia': 2906.976806640625,
               'safetyConfigs': [{'safetyModel': 'noOutput', 'safetyParam': 0, 'safetyParam2DEPRECATED': 0, 'safetyParamDEPRECATED': 0}],
               'safetyModelDEPRECATED': 'silent',
               'safetyModelPassiveDEPRECATED': 'silent',
               'safetyParamDEPRECATED': 0,
               'startAccel': 0.0,
               'startingAccelRateDEPRECATED': 0.0,
               'startingState': False,
               'steerActuatorDelay': 0.0,
               'steerControlType': 'torque',
               'steerLimitAlert': False,
               'steerLimitTimer': 1.0,
               'steerRateCostDEPRECATED': 0.0,
               'steerRatio': 13.0,
               'steerRatioRear': 0.0,
               'stopAccel': -2.0,
               'stoppingControl': True,
               'stoppingDecelRate': 0.800000011920929,
               'tireStiffnessFactor': 0.0,
               'tireStiffnessFront': 1000000.0,
               'tireStiffnessRear': 1000000.0,
               'transmissionType': 'unknown',
               'vEgoStarting': 0.5,
               'vEgoStopping': 0.5,
               'wheelSpeedFactor': 1.0,
               'wheelbase': 2.700000047683716},
 'logMonoTime': 86561053128,
 'valid': True}

**Comment by tmcmenam** [comment]
@sunnyhaibin can you approve this PR? and double check what I added =)

**Comment by vincentw56** [comment]
@tmcmenam These values need to be upstreamed into OP. Can you provide your dongle ID?

**Comment by tmcmenam** [comment]
@vincentw56 Dongle ID is 0f88f104416b674a

**Comment by grangeg** [comment]
Is anything else needed to merge this pull request?

**Pull request closed without merging**
